### ISSUE TITLE
I added types to aki-api

### ISSUE THREAD

**Issue by jgoralcz** [SpiderMath/Aki-API.ts#1]
Hey! I just wanted to say it's cool that you added types!

I didn't know this was requested until recently, but I added types to aki-api.

I'm new to typescript, so any feedback helps!

**Comment by SpiderMath** [comment]
Note: Sorry for the late response, wasn't on GitHub as such yesterday. 

Thanks for doing that, now I can archive this repository. I'd made this repository only to fulfil the need for some Typings in the Package, since I mostly work with TypeScript and packages without Typings cannot be used in TypeScript projects.
